### ISSUE TITLE
[Refactor] Home, Login, Todo, Dday 수정

### ISSUE THREAD

**Issue by seoin-cho** [SoluxProject/client#5]
- [x] Home, Login, Todo, Dday 응답 수정
- [x] 투두, 디데이 아직 없을 경우에 대한 액션 추가
- [x] Home css 수정

**Comment by seoin-cho** [comment]
#6
